POST http://localhost:3000/signup HTTP/1.1
content-type: application/json

{
    "email": "furkanozbek@gmail.com",
    "password": "furkan123",
    "name": "Furkan"
}

###

POST http://localhost:3000/login HTTP/1.1

{
    "email": "furkanozbek@gmail.com",
    "password": "furkan123"
}

###
POST http://localhost:3000/query HTTP/1.1

{
    "query": "select * from users",
    "hash": "randomhash"
}